# Generated by Django 2.0.3 on 2018-04-20 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete='Cascade', to=settings.AUTH_USER_MODEL),
        ),
    ]
