# Generated by Django 2.0.3 on 2018-04-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20180420_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
